# version: "3.7"

# networks:
#   default:
#     name: home_service
#     driver: bridge

services:


  # https://docs.linuxserver.io/images/docker-jellyfin
  jellyfin:
    # image: lscr.io/linuxserver/jellyfin:nightly
    image: nyanmisaka/jellyfin:latest
    container_name: jellyfin
    environment:
      - TZ=${TZ}
      - PUID=${PUID}
      - PGID=${PGID}
      - JELLYFIN_PublishedServerUrl='' #optional
    volumes:
      - ${BASE_DATA_DIR}/jellyfin:/config
      - ${BASE_CACHE_DIR}/jellyfin/cache:/cache
      - ${BASE_CACHE_DIR}/jellyfin/metadata:/config/metadata
      - ${BASE_CACHE_DIR}/jellyfin/transcodes:/config/transcodes
      - ${MEDIA_LIB_DIR}:/storage
    restart: ${BASE_RESTART_STRATEGY}  
    ports:
      - ${JELLYFIN_WEB_8096}:8096
      # - 8920:8920 #optional https
      - ${JELLYFIN_PORT_7359}:7359/udp #optional clients discovery
      - ${JELLYFIN_PORT_1900}:1900/udp #optional DNLA


  plex:
    image: lscr.io/linuxserver/plex:latest
    container_name: plex
    environment:
      - TZ=${TZ}
      - PUID=${PUID}
      - PGID=${PGID}
      - VERSION=docker
      - PLEX_CLAIM=${PLEX_CLAIM}
    volumes:
      - ${BASE_DATA_DIR}/plex:/config
      - ${MEDIA_LIB_DIR}:/storage
    restart: ${BASE_RESTART_STRATEGY}  
    ports:
      - ${PLEX_WEB_32400}:32400
