version: "3"

networks:
  default:
    name: home_service
    # enable_ipv6: true
    # driver_opts:
    #   com.docker.network.enable_ipv6: "true"
    driver: bridge

      

services:

  test_ipv6:
    image: busybox
    command: ping6 -c 4 google.com
    profiles: [disabled]
    logging:
      driver: json-file
      options:
        max-file: ${BASE_LOGGING_MAXFILE}
        max-size: ${BASE_LOGGING_MAXSIZE}
    environment:
      - TZ=${TZ}
      - PUID=${PUID}
      - PGID=${PGID}
    volumes:
      - ${BASE_DATA_DIR}/test_ipv6:/data
      - ${BASE_CACHE_DIR}/test_ipv6:/cache