services:
  # https://docs.linuxserver.io/images/docker-jellyfin
  jellyfin:
    # image: lscr.io/linuxserver/jellyfin:nightly
    image: nyanmisaka/jellyfin:latest
    container_name: jellyfin
    environment:
      - TZ=${TZ}
      - PUID=${PUID}
      - PGID=${PGID}
      - JELLYFIN_PublishedServerUrl='' #optional
    volumes:
      - ${BASE_DATA_DIR}/jellyfin:/config
      - ${BASE_CACHE_DIR}/jellyfin/cache:/cache
      - ${BASE_CACHE_DIR}/jellyfin/metadata:/config/metadata
      - ${BASE_CACHE_DIR}/jellyfin/transcodes:/config/transcodes
      - ${MEDIA_LIB_DIR}:/storage
    restart: ${BASE_RESTART_STRATEGY}  
    ports:
      - ${JELLYFIN_WEB_8096}:8096
      # - 8920:8920 #optional https
      - ${JELLYFIN_PORT_7359}:7359/udp #optional clients discovery
      - ${JELLYFIN_PORT_1900}:1900/udp #optional DNLA


  plex:
    image: lscr.io/linuxserver/plex:latest
    container_name: plex
      #user: "${PUID}:${PGID}"
    environment:
      - TZ=${TZ}
      - PUID=${PUID}
      - PGID=${PGID}
      - VERSION=docker
      - PLEX_CLAIM=${PLEX_CLAIM}
    volumes:
      - ${BASE_DATA_DIR}/plex:/config
      - ${MEDIA_LIB_DIR}:/storage
      - ${BASE_CACHE_DIR}/plex/transcodes:/cache/transcodes
    restart: ${BASE_RESTART_STRATEGY}  
    ports:
      - ${PLEX_WEB_32400}:32400


  emby:
    image: lscr.io/linuxserver/emby:latest
    container_name: emby
    environment:
      - TZ=${TZ}
      - PUID=${PUID}
      - PGID=${PGID}
    volumes:
      - ${BASE_CACHE_DIR}/emby/cache:/cache
      - ${BASE_CACHE_DIR}/emby/metadata:/config/metadata
      - ${BASE_CACHE_DIR}/emby/logs:/config/logs
      - ${BASE_CACHE_DIR}/emby/transcodes:/config/transcoding-temp
      - ${BASE_DATA_DIR}/emby:/config
      - ${MEDIA_LIB_DIR}:/storage
      - /opt/vc/lib:/opt/vc/lib #optional
    ports:
      - ${EMBY_WEB_8096}:8096
      - ${EMBY_8920}:8920 #optional
    devices:
      - /dev/dri:/dev/dri #optional
    restart: ${BASE_RESTART_STRATEGY}  
    

  # https://gitlab.com/Bockiii/deemix-docker
  deemix:
    image: registry.gitlab.com/bockiii/deemix-docker
    container_name: Deemix
    volumes:
      - ${BASE_DATA_DIR}/deemix:/config
      - ${MEDIA_LIB_DIR}:/storage
      - ${MEDIA_LIB_DIR}/Music/downloads:/downloads
    profiles: ["disabled"]
    environment:
      - TZ=${TZ}
      - PUID=${PUID}
      - PGID=${PGID}
      - DEEMIX_SINGLE_USER=true
    ports:
      - ${DEEMIX_WEB}:6595

