services:
  
  #https://github.com/SuperNG6/docker-aria2
  docker-aria2:
    container_name: docker-aria2
    image: superng6/aria2:webui-latest
    ports:
      - ${DOCKER_ARAI2_RPC_6800}:6800
      - ${DOCKER_ARAI2_P2P_6881}:6801
      - ${DOCKER_ARAI2_P2P_6881_UDP}:6801/udp
      - ${DOCKER_ARAI2_WEB_8080}:8080
      - ${DOCKER_ARAI2_BT_32516}:32516
    environment:
      - PGID=${PGID}
      - PUID=${PUID}
      - TZ=${TZ}
      - SECRET=${DOCKER_ARAI2_SECRET}
      - CACHE=1024M
      - WEBUI=true
      - WEBUI_PORT=8080
      - BTPORT=32516
      - UT=true
      - RUT=true
      - CTU=https://cdn.jsdelivr.net/gh/XIU2/TrackersListCollection@master/best_aria2.txt
      - SMD=true
      - FA=none
    logging:
      driver: json-file
      options:
        max-file: ${BASE_LOGGING_MAXFILE}
        max-size: ${BASE_LOGGING_MAXSIZE}
    restart: ${BASE_RESTART_STRATEGY}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${BASE_DATA_DIR}/docker-aria2:/config
      - ${MEDIA_LIB_DIR}:/storage

  qbittorrent:
    container_name: qbittorrent
    image: hotio/qbittorrent
    # network_mode: "service:gluetun"
    ports:
      - ${QBIT_MANAGE_PORT_8080}:8080
      - ${QBIT_PORT_9000}:9000
    environment:
      - PGID=${PGID}
      - PUID=${PUID}
      - TZ=${TZ}
    logging:
      driver: json-file
      options:
        max-file: ${BASE_LOGGING_MAXFILE}
        max-size: ${BASE_LOGGING_MAXSIZE}
    restart: ${BASE_RESTART_STRATEGY}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${BASE_DATA_DIR}/qbittorrent:/config
      - ${MEDIA_LIB_DIR}:/storage

  nzbget:
    image: lscr.io/linuxserver/nzbget
    ports:
      - ${NZBGET_PORT_6789:-6789}:6789
    container_name: nzbget
    environment:
      - PGID=${PGID}
      - PUID=${PUID}
      - TZ=${TZ}
      - NZBGET_USER=${NZBGET_USER:-admin}
      - NZBGET_PASS=${NZBGET_PASS:-admin}

    logging:
      driver: json-file
      options:
        max-file: ${BASE_LOGGING_MAXFILE}
        max-size: ${BASE_LOGGING_MAXSIZE}
    restart: ${BASE_RESTART_STRATEGY}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${BASE_DATA_DIR}/nzbget:/config
      - ${MEDIA_LIB_DIR}:/storage

  transmission:
    image: lscr.io/linuxserver/transmission
    ports:
      - ${TRANSMISSION_PORT_51413}:51413
      - ${TRANSMISSION_PORT_51413}:51413/udp
      - ${TRANSMISSION_PORT_6881}:6881
      - ${TRANSMISSION_PORT_6881}:6881/udp
      - ${TRANSMISSION_PORT_9091}:9091
    container_name: transmission
    environment:
      - PGID=${PGID}
      - PUID=${PUID}
      - TZ=${TZ}
    logging:
      driver: json-file
      options:
        max-file: ${BASE_LOGGING_MAXFILE}
        max-size: ${BASE_LOGGING_MAXSIZE}
    restart: ${BASE_RESTART_STRATEGY}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${BASE_DATA_DIR}/transmission:/config
      - ${MEDIA_LIB_DIR}:/storage
      - ${MEDIA_LIB_DIR}:/downloads

  metube:
    image: alexta69/metube
    container_name: metube
    logging:
      driver: json-file
      options:
        max-file: ${BASE_LOGGING_MAXFILE}
        max-size: ${BASE_LOGGING_MAXSIZE}
    restart: ${BASE_RESTART_STRATEGY}
    user: "${PUID}:${PGID}"
    environment:
      - PGID=${PGID}
      - PUID=${PUID}
      - TZ=${TZ}
      - YTDL_OPTIONS={"writesubtitles":true,"subtitleslangs":["en","cn","-live_chat"],"cookiefile":"/downloads/cookies.txt"}
      - OUTPUT_TEMPLATE_rem="%(playlist)s/%(playlist_index)s - %(title)s.%(ext)s"
      - OUTPUT_TEMPLATE="%(uploader)s/%(playlist)s/%(playlist_index)s - %(title)s.%(ext)s"
    ports:
      - ${METUBE_WEB_PORT_8081}:8081
    volumes:
      # - /path/to/cookies:/cookies #optionally specify cookies file, must named cookies.txt
      - ${MEDIA_LIB_DIR}/Youtube:/downloads
      - ${BASE_CACHE_DIR}/metube:/downloads/.metube

  ytdl_material:
    container_name: ytdl_material
    logging:
      driver: json-file
      options:
        max-file: ${BASE_LOGGING_MAXFILE}
        max-size: ${BASE_LOGGING_MAXSIZE}
    restart: ${BASE_RESTART_STRATEGY}
    user: "${PUID}:${PGID}"
    environment:
      - ALLOW_CONFIG_MUTATIONS='true'
      - GID=${PGID}
      - UID=${PUID}
      - PGID=${PGID}
      - PUID=${PUID}
      - TZ=${TZ}
    volumes:
      - ${MEDIA_LIB_DIR}/ytdl_material:/downloads
      - ${MEDIA_LIB_DIR}/ytdl_material/audio:/app/audio
      - ${MEDIA_LIB_DIR}/ytdl_material/video:/app/video
      - ${MEDIA_LIB_DIR}/ytdl_material/subscriptions:/app/subscriptions

      - ${BASE_DATA_DIR}/ytdl_material/appdata:/app/appdata
      - ${BASE_DATA_DIR}/ytdl_material/users:/app/users
    ports:
        - ${YTUBE_MATERIAL_WEB_PORT_17442}:17442
    image: tzahi12345/youtubedl-material:latest
