services:

  traefik:
    container_name: traefik
    image: "traefik:latest"
    command:
      - "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.docker"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=true"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443" 
      - "--certificatesresolvers.myresolver.acme.tlschallenge=true" 
      - "--certificatesresolvers.myresolver.acme.demains=derekzhu.asuscomm.com"
      - "--certificatesresolvers.myresolver.acme.email=1and1get2@gmail.com"
      - "--certificatesresolvers.myresolver.acme.storage=/etc/traefik/letsencrypt/acme.json"
    ports:
      - ${TRAEFIK_WEB_80}:80
      - ${TRAEFIK_WEB_443}:443
      - ${TRAEFIK_WEB_MANAGEMENT}:8080
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - ${BASE_DATA_DIR}/traefik:/etc/traefik

  whoami:
    image: "traefik/whoami"
    container_name: whoami
    labels:
      - "traefik.enable=true"
      # - "traefik.http.routers.whoami.rule=Host(`whoami.services.localhost`)"
      # - "traefik.http.routers.whoami.rule=Host(`whoami.localhost`)"
      # - "traefik.http.routers.whoami.rule=Host(`localhost`) && Path(`/whoami`)"
      # - "traefik.http.routers.whoami.rule=Host(`whoami.derekzhu.asuscomm.com`)"
      # - "traefik.http.routers.whoami.rule=Host(`derekzhu.asuscomm.com`)"
      # - "traefik.http.routers.whoami.rule=Host(`derekzhu.asuscomm.com`) && Path(`/whoami`)"
      # - "traefik.http.routers.whoami.rule=Host(`whoami.docker.localhost`)"
      - "traefik.http.routers.whoami.entrypoints=web,websecure"
      - "traefik.http.routers.whoami.tls.certresolver=myresolver"

  ddns_updater:
      image: qmcgaw/ddns-updater
      container_name: ddns-updater
      ports:
        - ${DDNS_UPDATER_WEB}:8000/tcp
      logging:
        driver: json-file
        options:
          max-file: ${BASE_LOGGING_MAXFILE}
          max-size: ${BASE_LOGGING_MAXSIZE}
      environment:
        - TZ=${TZ}
        - PUID=${PUID}
        - PGID=${PGID}
        - CONFIG=
        - PERIOD=5m
        - UPDATE_COOLDOWN_PERIOD=5m
        - PUBLICIP_FETCHERS=all
        - PUBLICIP_HTTP_PROVIDERS=all
        - PUBLICIPV4_HTTP_PROVIDERS=all
        # - PUBLICIPV6_HTTP_PROVIDERS=all
        - PUBLICIP_DNS_PROVIDERS=all
        - PUBLICIP_DNS_TIMEOUT=3s
        - HTTP_TIMEOUT=10s

        # Web UI
        - LISTENING_PORT=8000
        - ROOT_URL=/

        # Backup
        - BACKUP_PERIOD=0 # 0 to disable
        - BACKUP_DIRECTORY=/updater/data

        # Other
        - LOG_LEVEL=info
        - LOG_CALLER=hidden
        - SHOUTRRR_ADDRESSES=
      
      volumes:
        - ${BASE_DATA_DIR}/ddns_updater:/updater/data
        # - ${BASE_CACHE_DIR}/jellyfin/cache:/cache
      restart: ${BASE_RESTART_STRATEGY}  

