# DO NOT USE, NOT COMPLETE

services:
  app:
    environment:
      - PGID=${PGID}
      - PUID=${PUID}
      - TZ=${TZ}
    logging:
      driver: json-file
      options:
        max-file: ${BASE_LOGGING_MAXFILE}
        max-size: ${BASE_LOGGING_MAXSIZE}
    restart: ${BASE_RESTART_STRATEGY}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${MEDIA_LIB_DIR}:/storage

